name: Project U Server CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to the latest commit'
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: 'Run chmod to make gradlew executable'
        run: chmod +x ./gradlew
      - name: 'Build with Gradle'
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build -x test
      - name: 'Run chmod to make gradlew executable'
        run: chmod +x ./gradlew
      - name: 'Run Tests'
        run: ./gradlew test

  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: 'Stop and remove containers, networks'
        run: docker-compose down
      - name: 'Remove unused data'
        run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: 'Checkout to the latest commit'
        uses: actions/checkout@v3
      - name: 'Deploy containers'
        run: docker-compose up -d